In [1]:
import pandas as pd 
df = pd.read_csv('dirty_student_records.csv')
print('done')

done

In [2]:
df.head(10)

,Student ID,Department,Gender,Age,Theory Marks,Practical Marks,Total Marks,Attendance Percent,Scholarship,Admission Date
0,STU_3974650,Law,Female,21,22.0,24.0,ERROR,63.2,No,2024-07-10
1,STU_4381094,Science,Female,UNKNOWN,1.0,29.0,30.0,92.3,No,2022-09-16
2,STU_4440080,Medicine,Male,21,58.0,11.0,69.0,87.1,No,2022-10-29
3,STU_7294264,NaN,Female,25,UNKNOWN,2.0,32.0,90.4,No,2025-04-13
4,STU_7967958,Science,Female,17,30.0,22.0,52.0,82.9,No,NaN
5,STU_8212191,Medicine,Male,22,57.0,22.0,79.0,89.4,No,2023-10-04
6,STU_2304616,Engineering,Male,20,6.0,16.0,22.0,96.4,No,2023-04-21
7,STU_3851214,NaN,Female,25,15.0,12.0,27.0,ERROR,No,NaN
8,STU_8958922,Medicine,Female,19,31.0,26.0,57.0,79.6,No,2022-12-03
9,STU_2555005,ERROR,Male,19,57.0,8.0,65.0,61.1,Yes,2024-05-24

In [3]:
df.columns

Index(['Student ID', 'Department', 'Gender', 'Age', 'Theory Marks',
       'Practical Marks', 'Total Marks', 'Attendance Percent', 'Scholarship',
       'Admission Date'],
      dtype='str')

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Student ID          100000 non-null  str
 1   Department          92178 non-null   str
 2   Gender              91990 non-null   str
 3   Age                 97999 non-null   str
 4   Theory Marks        97980 non-null   str
 5   Practical Marks     97926 non-null   str
 6   Total Marks         96976 non-null   str
 7   Attendance Percent  97998 non-null   str
 8   Scholarship         91963 non-null   str
 9   Admission Date      98050 non-null   str
dtypes: str(10)
memory usage: 12.7 MB

In [5]:
df.isnull().sum()

Student ID               0
Department            7822
Gender                8010
Age                   2001
Theory Marks          2020
Practical Marks       2074
Total Marks           3024
Attendance Percent    2002
Scholarship           8037
Admission Date        1950
dtype: int64

In [6]:
df.duplicated().sum()
# no duplicates

np.int64(0)

In [7]:
col = list(df.columns)
col

['Student ID',
 'Department',
 'Gender',
 'Age',
 'Theory Marks',
 'Practical Marks',
 'Total Marks',
 'Attendance Percent',
 'Scholarship',
 'Admission Date']

In [8]:
# to replace error and unknown as null 
for i in col:
    df[i]=df[i].replace(["ERROR","UNKNOWN",""],pd.NA)

In [9]:
df.isnull().sum()

Student ID                0
Department            13985
Gender                14129
Age                    6011
Theory Marks           6030
Practical Marks        6170
Total Marks            8017
Attendance Percent     5877
Scholarship           14180
Admission Date         5890
dtype: int64

In [10]:
df.fillna({'Theory Marks':'0','Practical Marks':'0', 'Total Marks':'0', 'Attendance Percent':'0','Age':'0'},inplace = True)

,Student ID,Department,Gender,Age,Theory Marks,Practical Marks,Total Marks,Attendance Percent,Scholarship,Admission Date
0,STU_3974650,Law,Female,21,22.0,24.0,0,63.2,No,2024-07-10
1,STU_4381094,Science,Female,0,1.0,29.0,30.0,92.3,No,2022-09-16
2,STU_4440080,Medicine,Male,21,58.0,11.0,69.0,87.1,No,2022-10-29
3,STU_7294264,NaN,Female,25,0,2.0,32.0,90.4,No,2025-04-13
4,STU_7967958,Science,Female,17,30.0,22.0,52.0,82.9,No,NaN
...,...,...,...,...,...,...,...,...,...,...
99995,STU_9512566,Management,Male,23,59.0,21.0,80.0,93.9,No,2025-03-20
99996,STU_1450447,Commerce,Male,21,56.0,11.0,67.0,72.0,Yes,2024-09-17
99997,STU_7958701,Engineering,Male,23,28.0,26.0,54.0,61.5,No,2023-10-31
99998,STU_3683620,Medicine,NaN,24,17.0,2.0,19.0,72.3,NaN,2023-05-16
99999,STU_7234387,Arts,Female,21,0.0,6.0,6.0,88.6,No,2023-09-27

In [11]:
for i in col:
    print("column name: ",i,df[i].unique())
    print()
    print("*"*100)

column name:  Student ID <ArrowStringArray>
['STU_3974650', 'STU_4381094', 'STU_4440080', 'STU_7294264', 'STU_7967958',
 'STU_8212191', 'STU_2304616', 'STU_3851214', 'STU_8958922', 'STU_2555005',
 ...
 'STU_9622761', 'STU_4426630', 'STU_8869891', 'STU_1344320', 'STU_6037468',
 'STU_9512566', 'STU_1450447', 'STU_7958701', 'STU_3683620', 'STU_7234387']
Length: 100000, dtype: str

****************************************************************************************************
column name:  Department <ArrowStringArray>
[        'Law',     'Science',    'Medicine',           nan, 'Engineering',
        'Arts',  'Management',    'Commerce']
Length: 8, dtype: str

****************************************************************************************************
column name:  Gender <ArrowStringArray>
['Female', 'Male', nan]
Length: 3, dtype: str

****************************************************************************************************
column name:  Age <ArrowStringArray>
['21', '0', '25', '17', '22', '20', '19', '24', '23', '18']
Length: 10, dtype: str

****************************************************************************************************
column name:  Theory Marks <ArrowStringArray>
['22.0',  '1.0', '58.0',    '0', '30.0', '57.0',  '6.0', '15.0', '31.0',
 '49.0', '12.0', '59.0', '13.0', '16.0', '43.0', '17.0', '37.0', '18.0',
 '29.0', '20.0',  '8.0', '26.0', '50.0', '55.0', '34.0', '54.0',  '4.0',
 '28.0', '70.0', '63.0', '21.0', '40.0', '62.0', '60.0', '41.0',  '5.0',
 '39.0', '53.0', '44.0', '65.0',  '2.0',  '9.0', '36.0', '10.0', '64.0',
 '24.0', '51.0', '48.0', '23.0', '19.0', '42.0', '68.0',  '3.0', '46.0',
 '66.0', '69.0', '25.0',  '7.0',  '0.0', '33.0', '47.0', '32.0', '14.0',
 '35.0', '67.0', '38.0', '27.0', '45.0', '61.0', '52.0', '56.0', '11.0']
Length: 72, dtype: str

****************************************************************************************************
column name:  Practical Marks <ArrowStringArray>
['24.0', '29.0', '11.0',  '2.0', '22.0', '16.0', '12.0', '26.0',  '8.0',
    '0', '25.0',  '9.0',  '7.0', '17.0', '21.0',  '5.0', '19.0', '15.0',
 '18.0',  '4.0', '28.0',  '1.0', '30.0', '23.0', '10.0', '14.0',  '6.0',
 '13.0', '20.0', '27.0',  '3.0',  '0.0']
Length: 32, dtype: str

****************************************************************************************************
column name:  Total Marks <ArrowStringArray>
[    '0',  '30.0',  '69.0',  '32.0',  '52.0',  '79.0',  '22.0',  '27.0',
  '57.0',  '65.0',
 ...
   '4.0',  '94.0',   '2.0',  '88.0',  '97.0',  '99.0',   '5.0', '100.0',
   '1.0',   '0.0']
Length: 102, dtype: str

****************************************************************************************************
column name:  Attendance Percent <ArrowStringArray>
['63.2', '92.3', '87.1', '90.4', '82.9', '89.4', '96.4',    '0', '79.6',
 '61.1',
 ...
 '33.9', '41.2', '36.1', '39.8', '39.4', '31.2', '39.6', '32.7', '33.5',
 '43.5']
Length: 617, dtype: str

****************************************************************************************************
column name:  Scholarship <ArrowStringArray>
['No', 'Yes', nan]
Length: 3, dtype: str

****************************************************************************************************
column name:  Admission Date <ArrowStringArray>
['2024-07-10', '2022-09-16', '2022-10-29', '2025-04-13',          nan,
 '2023-10-04', '2023-04-21', '2022-12-03', '2024-05-24', '2024-02-14',
 ...
 '2023-01-08', '2025-03-04', '2024-10-22', '2022-10-18', '2023-09-06',
 '2022-07-21', '2025-03-07', '2024-07-14', '2025-04-08', '2022-09-30']
Length: 1096, dtype: str

****************************************************************************************************

In [12]:
col

['Student ID',
 'Department',
 'Gender',
 'Age',
 'Theory Marks',
 'Practical Marks',
 'Total Marks',
 'Attendance Percent',
 'Scholarship',
 'Admission Date']

In [13]:
df["Theory Marks"] = df["Theory Marks"].astype(float)
df["Practical Marks"] = df["Practical Marks"].astype(float)
df["Total Marks"] = df["Total Marks"].astype(float)
df["Attendance Percent"] = df["Attendance Percent"].astype(float)
df["Age"] = df["Age"].astype(int)

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Student ID          100000 non-null  str
 1   Department          86015 non-null   str
 2   Gender              85871 non-null   str
 3   Age                 100000 non-null  int64
 4   Theory Marks        100000 non-null  float64
 5   Practical Marks     100000 non-null  float64
 6   Total Marks         100000 non-null  float64
 7   Attendance Percent  100000 non-null  float64
 8   Scholarship         85820 non-null   str
 9   Admission Date      94110 non-null   str
dtypes: float64(4), int64(1), str(5)
memory usage: 10.8 MB

In [15]:
def zero_count(col_name):
    count = 0
    for i in df.index:
        if df.loc[i,col_name] == 0 or str (df.loc[i,col_name]) == "0":
            count +=1
    print(f"{col_name} zero count : {count}")

In [16]:
for i in col:
    zero_count(i)

Student ID zero count : 0
Department zero count : 0
Gender zero count : 0
Age zero count : 6011
Theory Marks zero count : 7323
Practical Marks zero count : 9296
Total Marks zero count : 8066
Attendance Percent zero count : 5877
Scholarship zero count : 0
Admission Date zero count : 0

In [17]:
  for i in df.index:
        if df.loc[i,'Theory Marks'] != 0 and df.loc [i,'Practical Marks'] != 0:
            df.loc[i,'Total Marks'] = df.loc[i,'Theory Marks'] + df.loc [i,'Practical Marks']
        else:
            pass

In [18]:
zero_count('Total Marks')

Total Marks zero count : 1336

In [24]:
zero_count('Total Marks')

Total Marks zero count : 1336

In [19]:
  for i in df.index:
        if df.loc[i,'Total Marks'] != 0 and df.loc [i,'Practical Marks'] != 0:
            df.loc[i,'Theory Marks'] = df.loc[i,'Total Marks'] - df.loc [i,'Practical Marks']
        else:
            pass

In [20]:
zero_count('Theory Marks')

Theory Marks zero count : 2356

In [26]:
zero_count('Theory Marks')

Theory Marks zero count : 2356

In [20]:
 for i in df.index:
        if df.loc[i,'Total Marks'] != 0 and df.loc [i,'Theory Marks'] != 0:
            df.loc[i,'Practical Marks'] = df.loc[i,'Total Marks'] - df.loc [i,'Theory Marks']
        else:
            pass

In [22]:
zero_count('Practical Marks')

Practical Marks zero count : 4112

In [26]:
zero_count('Practical Marks')

Practical Marks zero count : 3582

In [21]:
for i in df.index:
        if df.loc[i,'Practical Marks'] == 0 and df.loc [i,'Theory Marks'] == 0 and df.loc[i,'Total Marks'] != 0 :
            df.loc[i,'Theory Marks'] = (df.loc[i,'Total Marks'] * 0.7).round() 
        else:
            pass

In [24]:
zero_count('Theory Marks')

Theory Marks zero count : 1821

In [22]:
 for i in df.index:
        if df.loc[i,'Total Marks'] != 0 and df.loc [i,'Theory Marks'] != 0:
            df.loc[i,'Practical Marks'] = df.loc[i,'Total Marks'] - df.loc [i,'Theory Marks']
        else:
            pass

In [28]:
for i in col:
    zero_count(i)

Student ID zero count : 0
Department zero count : 0
Gender zero count : 0
Age zero count : 6011
Theory Marks zero count : 1821
Practical Marks zero count : 3582
Total Marks zero count : 1336
Attendance Percent zero count : 5877
Scholarship zero count : 0
Admission Date zero count : 0

In [23]:
tmed = df['Theory Marks'].median()
print(f"{'Theory Marks'}: median = {tmed}")
pmed = df['Practical Marks'].median()
print(f"{'Practical Marks'}: median = {pmed}")

Theory Marks: median = 35.0
Practical Marks: median = 15.0

In [24]:
df['Practical Marks'] = df['Practical Marks'].replace(0, pmed)
df['Theory Marks'] = df['Theory Marks'].replace(0, tmed)

In [25]:
for i in col:
    zero_count(i)

Student ID zero count : 0
Department zero count : 0
Gender zero count : 0
Age zero count : 6011
Theory Marks zero count : 0
Practical Marks zero count : 0
Total Marks zero count : 1336
Attendance Percent zero count : 5877
Scholarship zero count : 0
Admission Date zero count : 0

In [26]:
  for i in df.index:
        if df.loc[i,'Theory Marks'] != 0 and df.loc [i,'Practical Marks'] != 0:
            df.loc[i,'Total Marks'] = df.loc[i,'Theory Marks'] + df.loc [i,'Practical Marks']
        else:
            pass

In [41]:
zero_count('Total Marks')

Total Marks zero count : 0

In [27]:
a_med = df['Age'].median()
print(f"{'Age'}: median = {a_med}")
at_med = df['Attendance Percent'].median()
print(f"{'Attendance Percent'}: median = {at_med}")

Age: median = 21.0
Attendance Percent: median = 79.1

In [28]:
df['Age'] = df['Age'].replace(0, a_med)
df['Attendance Percent'] = df['Attendance Percent'].replace(0, at_med)

In [29]:
for i in col:
    zero_count(i)

Student ID zero count : 0
Department zero count : 0
Gender zero count : 0
Age zero count : 0
Theory Marks zero count : 0
Practical Marks zero count : 0
Total Marks zero count : 0
Attendance Percent zero count : 0
Scholarship zero count : 0
Admission Date zero count : 0

In [30]:
df.isnull().sum()

Student ID                0
Department            13985
Gender                14129
Age                       0
Theory Marks              0
Practical Marks           0
Total Marks               0
Attendance Percent        0
Scholarship           14180
Admission Date         5890
dtype: int64

In [31]:
df['Department'].unique()

<ArrowStringArray>
[        'Law',     'Science',    'Medicine',           nan, 'Engineering',
        'Arts',  'Management',    'Commerce']
Length: 8, dtype: str

In [32]:
df['Department'].value_counts(dropna=False)

Department
NaN            13985
Law            12465
Medicine       12418
Arts           12282
Commerce       12274
Engineering    12261
Management     12193
Science        12122
Name: count, dtype: int64

In [33]:
import random

In [34]:
dept=['Law','Science','Medicine','Engineering','Arts','Management','Commerce']
df['Department'] = df['Department'].apply (lambda x : random.choice(dept) if pd.isna(x) else x)

In [35]:
df['Department'].value_counts(dropna=False)

Department
Law            14460
Medicine       14458
Arts           14329
Commerce       14251
Engineering    14245
Management     14222
Science        14035
Name: count, dtype: int64

In [36]:
df.isnull().sum()

Student ID                0
Department                0
Gender                14129
Age                       0
Theory Marks              0
Practical Marks           0
Total Marks               0
Attendance Percent        0
Scholarship           14180
Admission Date         5890
dtype: int64

In [37]:
df['Gender'].value_counts(dropna=False)

Gender
Female    42995
Male      42876
NaN       14129
Name: count, dtype: int64

In [38]:
gen = ['Male','Female']
df['Gender'] = df['Gender'].apply (lambda x : random.choice(gen) if pd.isna(x) else x)

In [39]:
df['Gender'].value_counts(dropna=False)

Gender
Female    50090
Male      49910
Name: count, dtype: int64

In [40]:
df.isnull().sum()

Student ID                0
Department                0
Gender                    0
Age                       0
Theory Marks              0
Practical Marks           0
Total Marks               0
Attendance Percent        0
Scholarship           14180
Admission Date         5890
dtype: int64

In [41]:
a_mod = df['Admission Date'].value_counts().head(10)
print(f"{'Admission Date'}: mode = {a_mod}")

Admission Date: mode = Admission Date
2024-04-13    116
2024-03-31    113
2024-04-21    111
2024-12-31    111
2025-05-30    110
2023-07-25    109
2023-03-19    109
2023-12-27    108
2025-04-28    108
2024-03-15    108
Name: count, dtype: int64

In [42]:
ran_date = ['2024-04-13','2024-03-31','2024-04-21','2024-12-31','2025-05-30','2023-07-25','2023-03-19','2023-12-27','2025-04-28','2024-03-15']
df['Admission Date'] = df['Admission Date'].apply (lambda x : random.choice(ran_date) if pd.isna(x) else x)

In [43]:
df.isnull().sum()

Student ID                0
Department                0
Gender                    0
Age                       0
Theory Marks              0
Practical Marks           0
Total Marks               0
Attendance Percent        0
Scholarship           14180
Admission Date            0
dtype: int64

In [45]:
df.fillna({'Scholarship':'UNKNOWN'},inplace = True )

,Student ID,Department,Gender,Age,Theory Marks,Practical Marks,Total Marks,Attendance Percent,Scholarship,Admission Date
0,STU_3974650,Law,Female,21,22.0,24.0,46.0,63.2,No,2024-07-10
1,STU_4381094,Science,Female,21,1.0,29.0,30.0,92.3,No,2022-09-16
2,STU_4440080,Medicine,Male,21,58.0,11.0,69.0,87.1,No,2022-10-29
3,STU_7294264,Management,Female,25,30.0,2.0,32.0,90.4,No,2025-04-13
4,STU_7967958,Science,Female,17,30.0,22.0,52.0,82.9,No,2024-03-31
...,...,...,...,...,...,...,...,...,...,...
99995,STU_9512566,Management,Male,23,59.0,21.0,80.0,93.9,No,2025-03-20
99996,STU_1450447,Commerce,Male,21,56.0,11.0,67.0,72.0,Yes,2024-09-17
99997,STU_7958701,Engineering,Male,23,28.0,26.0,54.0,61.5,No,2023-10-31
99998,STU_3683620,Medicine,Male,24,17.0,2.0,19.0,72.3,UNKNOWN,2023-05-16
99999,STU_7234387,Arts,Female,21,35.0,6.0,41.0,88.6,No,2023-09-27

In [46]:
df.isnull().sum()

Student ID            0
Department            0
Gender                0
Age                   0
Theory Marks          0
Practical Marks       0
Total Marks           0
Attendance Percent    0
Scholarship           0
Admission Date        0
dtype: int64

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Student ID          100000 non-null  str
 1   Department          100000 non-null  str
 2   Gender              100000 non-null  str
 3   Age                 100000 non-null  int64
 4   Theory Marks        100000 non-null  float64
 5   Practical Marks     100000 non-null  float64
 6   Total Marks         100000 non-null  float64
 7   Attendance Percent  100000 non-null  float64
 8   Scholarship         100000 non-null  str
 9   Admission Date      100000 non-null  str
dtypes: float64(4), int64(1), str(5)
memory usage: 11.1 MB

In [49]:
df.head(20)

,Student ID,Department,Gender,Age,Theory Marks,Practical Marks,Total Marks,Attendance Percent,Scholarship,Admission Date
0,STU_3974650,Law,Female,21,22.0,24.0,46.0,63.2,No,2024-07-10
1,STU_4381094,Science,Female,21,1.0,29.0,30.0,92.3,No,2022-09-16
2,STU_4440080,Medicine,Male,21,58.0,11.0,69.0,87.1,No,2022-10-29
3,STU_7294264,Management,Female,25,30.0,2.0,32.0,90.4,No,2025-04-13
4,STU_7967958,Science,Female,17,30.0,22.0,52.0,82.9,No,2024-03-31
5,STU_8212191,Medicine,Male,22,57.0,22.0,79.0,89.4,No,2023-10-04
6,STU_2304616,Engineering,Male,20,6.0,16.0,22.0,96.4,No,2023-04-21
7,STU_3851214,Management,Female,25,15.0,12.0,27.0,79.1,No,2023-07-25
8,STU_8958922,Medicine,Female,19,31.0,26.0,57.0,79.6,No,2022-12-03
9,STU_2555005,Law,Male,19,57.0,8.0,65.0,61.1,Yes,2024-05-24
10,STU_3433808,Law,Female,22,49.0,3.0,52.0,95.8,No,2024-02-14
11,STU_8122570,Medicine,Female,24,12.0,29.0,41.0,92.2,No,2023-07-22
12,STU_8313190,Arts,Male,20,22.0,25.0,47.0,77.3,No,2023-11-15
13,STU_4029225,Management,Female,19,59.0,9.0,68.0,78.9,UNKNOWN,2025-05-30
14,STU_7981237,Management,Female,21,58.0,22.0,80.0,69.2,No,2022-08-01
15,STU_2703328,Law,Male,23,13.0,7.0,20.0,92.1,No,2025-02-17
16,STU_9388885,Commerce,Male,22,1.0,22.0,23.0,87.6,No,2024-05-21
17,STU_4618801,Arts,Male,20,11.0,17.0,28.0,80.0,No,2025-04-26
18,STU_8774604,Arts,Male,21,12.0,21.0,33.0,91.4,No,2023-02-09
19,STU_1250220,Commerce,Male,19,16.0,9.0,25.0,68.2,No,2025-04-26

In [50]:
df.to_csv("clean_student_records.csv", index=False)
print("Saved", df.shape, "to clean_student_records.csv")
df.head(10)

Saved (100000, 10) to clean_student_records.csv

,Student ID,Department,Gender,Age,Theory Marks,Practical Marks,Total Marks,Attendance Percent,Scholarship,Admission Date
0,STU_3974650,Law,Female,21,22.0,24.0,46.0,63.2,No,2024-07-10
1,STU_4381094,Science,Female,21,1.0,29.0,30.0,92.3,No,2022-09-16
2,STU_4440080,Medicine,Male,21,58.0,11.0,69.0,87.1,No,2022-10-29
3,STU_7294264,Management,Female,25,30.0,2.0,32.0,90.4,No,2025-04-13
4,STU_7967958,Science,Female,17,30.0,22.0,52.0,82.9,No,2024-03-31
5,STU_8212191,Medicine,Male,22,57.0,22.0,79.0,89.4,No,2023-10-04
6,STU_2304616,Engineering,Male,20,6.0,16.0,22.0,96.4,No,2023-04-21
7,STU_3851214,Management,Female,25,15.0,12.0,27.0,79.1,No,2023-07-25
8,STU_8958922,Medicine,Female,19,31.0,26.0,57.0,79.6,No,2022-12-03
9,STU_2555005,Law,Male,19,57.0,8.0,65.0,61.1,Yes,2024-05-24